version: '3.8'

services:
  flask_model_server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./local_storage:/storage
    deploy:
      resources:
        limits:
          cpus: '7'
          memory: 19G
        reservations:
          cpus: '4'
          memory: 10G
    environment:
      - LOCAL_RUN=false
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - JOBLIB_TEMP_FOLDER=/tmp
      - JOBLIB_MAX_NBYTES=512M
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped 