version: '3.8'

services:
  flask_model_server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./local_storage:/storage
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    environment:
      - LOCAL_RUN=false
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 