version: '3.8'

services:
  flask_model_server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./local_storage:/storage
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 24G
          memory-swap: 48G
        reservations:
          cpus: '6'
          memory: 12G
    environment:
      - LOCAL_RUN=false
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - JOBLIB_TEMP_FOLDER=/tmp
      - JOBLIB_MAX_NBYTES=1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped 