version: "3.8"

services:
  flask_model_server:
    build:
      context: ./flask_model_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - training_artifacts:/storage/training_artifacts
      - mlflow_logs:/storage/mlflow_logs
      - params:/storage/params
      - data:/storage/data

  mlflow_server:
    build:
      context: ./mlflow_server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - training_artifacts:/storage/training_artifacts
      - mlflow_logs:/storage/mlflow_logs
      - data:/storage/data

volumes:
  mlflow_logs: 
  training_artifacts: 
  params:
  data: